# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7997760eaa296f1da495cdd73543ee7ba70cd2030f26c14bad4f503a16d18f2ad28ded3d930066a2c14040d1ab2796710d781ab884a3de1fbb18a4e696b26977

test:
  secret_key_base: 8fb758448552635e166c2d8526cb550ebb99bf6606f8f8d05da3fd2052e73c8815b22e866d169343a2b0d377145f7f52b71ea1f10f8f3c7ebfd0f283c3b7e5d7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
